apiVersion: kubernetes.inveniem.com/storage-config-transformer/v1alpha
kind: StorageConfigTransformer
metadata:
  name: storage-config-transformer
  annotations:
    config.kubernetes.io/function: |
      container:
        image: inveniem/kustomize-storage-transformer:latest
spec:
  - permutations:
      values:
        - sample-project1
        - sample-project2
        - sample-project3

    persistentVolumeTemplate:
      spec:
        capacity:
          storage: 1Ti
        accessModes:
          - ReadWriteMany
        azureFile:
          secretName: "myapp-azure-files-creds"
          shareName: "<<INJECTED>>"
      name:
        prefix: "pv-myapp-live-"
        suffix: ~
      injectedValues:
        # "targetField" is the new name for "field" from v1.0.0. Both "field"
        # and "targetField" are allowed in v1.1.0+, but "field" is deprecated
        # and "targetField" will be supported as the clearer option going
        # forward.
        - targetField: "spec.azureFile.shareName"
          prefix: ~
          suffix: ~

    persistentVolumeClaimTemplate:
      spec:
        storageClassName: ""
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Ti
        volumeName: "<<INJECTED>>"
      name:
        prefix: pvc-
        suffix: ~
        replacements:
          - pattern: '/sample\-/'
            replacement: ''
      namespace: sample
      injectedValues:
        # "targetField" is the new name for "field" from v1.0.0. Both "field"
        # and "targetField" are allowed in v1.1.0+, but "field" is deprecated
        # and "targetField" will be supported as the clearer option going
        # forward.
        - targetField: "spec.volumeName"
          prefix: "pv-myapp-live-"
          suffix: ~

    containerVolumeTemplates:
      - containers:
          - name: frontend-myapp
          - name: backend-myapp-api

        volumeTemplates:
          - mergeSpec:
              persistentVolumeClaim:
                claimName: "<<INJECTED>>"
            name:
              prefix: "vol-"
              suffix: ~
            injectedValues:
              # "targetField" is the new name for "field" from v1.0.0. Both
              # "field" and "targetField" are allowed in v1.1.0+, but
              # "targetField" will be supported as the clearer option going
              # forward.
              - targetField: "persistentVolumeClaim.claimName"
                prefix: "pvc-"
                suffix: ~
                replacements:
                  - pattern: '/sample\-/'
                    replacement: ''

        volumeMountTemplates:
          - mergeSpec:
              mountPath: "<<INJECTED>>"
            name:
              prefix: "vol-"
              suffix: ~
            injectedValues:
              # "targetField" is the new name for "field" from v1.0.0. Both
              # "field" and "targetField" are allowed in v1.1.0+, but
              # "targetField" will be supported as the clearer option going
              # forward.
              - targetField: "mountPath"
                prefix: "/mnt/share/"
                suffix: ~
                replacements:
                  - pattern: '/\-/'
                    replacement: '/'
